name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup ASP .NET
      uses: nuget/setup-nuget@v1
      with: 
        nuget-version: ${{env.NUGET_VERSION}}
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Restore dependencies
      run: dotnet restore /P0WebUI
    - name: Build
      run: dotnet build /P0WebUI --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish /P0WebUI --configuration Release -o ./publish
    - name: Deploy 1
      uses: azure/webapps-deploy@v2
      with: 
        app-name: 211004-Project-Web-App
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        package: ./publish
